name: vmps
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - python=3.7.12
  - pytorch=1.8.1
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - pip=22.3.1
  - pip:
      - av==10.0.0
      - einops==0.6.1
      - h5py==3.8.0
      - matplotlib==3.5.3
      - opencv-python==4.10.0.84
      - psutil==5.9.0
      - scikit-learn==1.0.2
      - simplejson==3.19.3
      - tensorboard==2.11.2
      - timm==0.9.12
      - wandb==0.17.9
      - git+https://github.com/facebookresearch/fvcore # for fvcore