name: vmps
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.8.1
  - torchvision=0.9.1
  - torchaudio=0.8.1
  - cudatoolkit=10.2
  - pip=22.3.1
  - pip:
      - av
      - einops
      - h5py
      - matplotlib
      - opencv-python
      - psutil
      - scikit-learn
      - simplejson
      - tensorboard
      - timm
      - wandb
      - git+https://github.com/facebookresearch/fvcore # for fvcore